RUN apt-get update \ && apt-get install -y ca-certificates \ && rm -rf /var/lib/apt/lists/*

# As opposed to:
# RUN apt-get update
# RUN apt-get install -y ca-certificates
# RUN rm -rf /var/lib/apt/lists/*