---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    # Syntax check will pass whether or not this file exists.
    - include_tasks: dates.yml

    - import_tasks: free.yml

    - name: Print a debug message.
      debug:
        msg: "Hello there."

    # Syntax check can't test against dynamic includes because dynamic includes operates at -run-time