---
- name: Install Apache on CentOS
  hosts: centos
  become: true

  tasks:
#    - name: Install Apache
#      command: yum install --quiet -y httpd httpd-devel

    - name: Install Apache
      yum:
        name:
          - httpd
          - httpd-devel
        state: present

#    - name: Copy configuration files.
#      command: > 
#        cp httpd.conf /etc/httpd/conf/httpd.conf
#    - command: >
#        cp httpd-vhosts /etc/httpd/conf/httpd-vhosts.conf

    - name: Copy configuration files.
      copy:
        src: "{{item.src}}"
        dest: "{{item.src}}"
        owner: root
        group: root
        mode: 0664
      with_items:
       - src: httpd.conf
         dest: /etc/httpd/conf/httpd.conf
       - src: httpd-vhosts.conf
         dest: /etc/httpd/conf/httpd-vhosts.conf

#    - name: Start Apache and configuration to run at boot.
#      command: service httpd start
#    - command: chkconfig httpd on

    - name: Make sure Apache is started now and at boot.
      service:
        name: httpd
        state: started
        enabled: true

# You can start dumping shell commands when first migrating over to Ansible
# shell: |
#   yum install --quiet -y httpd httpd-develp
#   cp httpd.conf /etc/httpd/conf/httpd.conf
#   cp hpd-vhosts /etc/httpd/conf/httpd-vhosts.conf
