---
- name: Install Apache
  hosts: centos
  become: yes

  # Global Environment
  # environment:
  # http_proxy: http://example-proxy:80/
  # https_proxy: https://example-proxy:443/

  # Variable Files
  # var_files:
  # - var.yml

  handlers:
    - name: restart apache
      service: 
        name: httpd
        state: restarted
      notify: restart memcached
      # you can use notify for other handlers

    - name: restart memcached
      service:
        name: memcached
        state: restarted
  
  tasks:
    - name: Download a file.
      get_url:
        url: https://ipv4.download.thinkbroadband.com/20MB.zip
        dest: /tmp
        # Local Environment
        # environment:
        #  http_proxy: http://example-proxy:80/
        #  https_proxy: https://example-proxy:443/
    - name: Add an environment variable.
      lineinfile:
        dest: "~/.bash_profile"
        regexp: '^ENV_VAR= '
        line: 'ENV_VAR=value'
      become: false 
      #use "become: false here" since "become: true" will use the root user bash profile

    - name: Get the value of an environment variable
      shell: 'source ~/.bash_profile && echo $ENV_VAR'
      register: foo

    - debug: msg="The variable is {{ foo.stdout }}"

    - name: Install Memcached.
      yum:
        name: memcached
        state: present

    - name: Install Apache.
      yum:
        name: httpd
        state: present

    - name: Copy test config file.
      copy:
        src: files/test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: 
      - restart apache
      # - restart memcached

    - name: Make sure handlers are flushed immediately.
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot.
      service:
        name: httpd
        state: started
        enabled: true

    - name: Ensure Memcached is running and starts at boot.
      service:
        name: memcached
        state: started
        enabled: true

    # - fail:
    # You can use fail module to directly fail the playbook
