---
- name: security 101
  hosts: selinux
  become: true

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted

  tasks:
    - meta: noop

    - name: Update yum cache.
      yum:
        update_cache: yes

    - name: Update CentOS.
      yum:
        name: '*'
        state: latest

    - name: Setup autoupdates.
      dnf:
        name: dnf-automatic
        state: present

    - name: Ensure autoupdates are running.
      service:
        name: dnf-automatic-install.timer
        state: started
        enabled: yes

# For CentOS 7
#    - name: Setup autoupdates.
#      yum:
#        name: yum-cron
#        state: present
#
#    - name: Ensure autoupdates are running.
#      service:
#        name: yum-cron
#        state: started
#        enabled: yes

# Required for managing Centos 8 on Ansible

    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Configure ports in firewall.
      firewalld:
        state: "{{ item.state }}"
        port: "{{ item.port }}"
        zone: external
        immediate: true
        permanent: true
      with_items:
        - { state: 'enabled', port: 2849/tcp }
        - { state: 'enabled', port: 123/udp }

    - name: Install libselinux-python.
      yum:
        name: python3-libselinux
        state: present

    - name: Install policycoreutils-python-utils.
      yum:
        name: policycoreutils-python-utils
        state: present

    - name: Tell SELinux about SSH's new port.
      seport:
        ports: 2849
        proto: tcp
        setype: ssh_port_t
        state: present

    - name: Make sure SSH is more secure.
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: 'sshd -T -f %s'
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^Port"
          line: "Port 2849"
      notify: restart ssh

    - name: Add user johndoe.
      user:
        name: johndoe

    - name: Add sudo group rights for deployment user.
      lineinfile:
        dest: /etc/sudoers
        regexp: '^johndoe'
        line: 'johndoe ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'

    - name: remove unused packages.
      package:
        name:
          - httpd
          - nvim
          - mailutils
        state: absent

    - name: Edit file permissions.
      file:
        path: /etc/ssh/sshd_config
        mode: 0600
