---
- name: Converge
  hosts: all
  tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

- import_playbook: ../../molecule.yml
    # - name: "Include episode8"
    #   include_role:
    #     name: "episode8"
