---
- name: Install Apache.
  hosts: all
  become: true

  handlers:
    - import_tasks: handlers/apache.yml

  pre_tasks:
    - name: Load variable files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yml"
        - "vars/apache_default.yml"

  tasks:
    - import_tasks: tasks/apache.yml
      # you can override the variable and locally set it using vars in import_tasks
      # vars:
      #   apache_package: apache3

- import_playbook: app.yml